spring:
  application:
    name: dividend

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"